"""
Module: data_pipeline.py
Author: Prateek Agrawal
Description: Core data engineering pipeline handling synthetic shell generation, 
             quantum-native positive control labeling, and rebalanced real-world 
             fraud data loading with disk-based persistence caching.
"""

import os
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
import config

class QKEDataPipeline:
    def __init__(self, seed=config.SEED):
        self.rng = np.random.default_rng(seed)
        self.seed = seed

    def generate_synthetic_shells(self, n_per_class=config.N_PER_CLASS_SYNTH, radii=config.SYNTH_RADII, noise=config.SYNTH_NOISE):
        """Primary synthetic dataset: Concentric hyperspherical shells."""
        d = config.QUBIT_BUDGET  # Dimensions match the maximum qubit budget limit exactly
        X, y = [], []
        for label, r in enumerate(radii):
            v = self.rng.normal(size=(n_per_class, d))
            v /= np.linalg.norm(v, axis=1, keepdims=True)
            r_noisy = r + noise * self.rng.normal(size=(n_per_class, 1))
            X.append(v * r_noisy)
            y.append(np.full(n_per_class, label))
        return np.vstack(X), np.concatenate(y)

    def generate_quantum_native(self, X_all, qkernel, n_anchors=config.N_ANCHORS, margin_percentage=config.MARGIN_PERCENTAGE):
        """Positive control dataset: Labels generated by the quantum kernel itself."""
        n_samples = len(X_all)
        if n_anchors > n_samples:
            raise ValueError("n_anchors cannot exceed total samples.")
            
        anchor_indices = self.rng.choice(n_samples, size=n_anchors, replace=False)
        X_ref = X_all[anchor_indices]
        
        alpha = self.rng.normal(size=n_anchors)
        kernel_matrix = qkernel.evaluate(x_vec=X_all, y_vec=X_ref)
        f = kernel_matrix @ alpha
        
        median_f = np.median(f)
        y_qc = (f > median_f).astype(int)
        
        margin = margin_percentage * np.std(f)
        clean_mask = np.abs(f - median_f) > margin
        
        return X_all[clean_mask], y_qc[clean_mask]

    def load_and_rebalance_real_data(self, csv_path=config.CSV_PATH, ratio=config.REAL_DATA_RATIO):
        """
        Secondary dataset: Loads CSV and balances class distributions.
        Optimized via Caching: Automatically writes out a balanced snapshot on the 
        first run to skip random downsampling iterations on subsequent runs.
        """
        base, ext = os.path.splitext(csv_path)
        balanced_csv_path = f"{base}_balanced{ext}"
        
        # Check if the balanced dataset is already stored in workspace space
        if os.path.exists(balanced_csv_path):
            print(f"   [Data Pipeline] Pre-balanced cache found at '{balanced_csv_path}'. Loading directly...")
            df_balanced = pd.read_csv(balanced_csv_path)
            y_balanced = df_balanced.iloc[:, 0].to_numpy()
            X_balanced = df_balanced.iloc[:, 1:].to_numpy()
            return X_balanced, y_balanced

        print(f"   [Data Pipeline] Pre-balanced cache not found. Rebalancing raw file at '{csv_path}'...")
        df = pd.read_csv(csv_path)
        
        y_raw = df.iloc[:, 0].to_numpy()
        X_raw = df.iloc[:, 1:].to_numpy()
        
        pos = np.where(y_raw == 1)[0]
        neg = np.where(y_raw == 0)[0]
        
        # Extract target sample volume mapping the minority profile ratio limits
        k = min(int(len(pos) * ratio), len(neg))
        neg_sampled = self.rng.choice(neg, size=k, replace=False)
        
        # Construct shuffle arrays
        idx = self.rng.permutation(np.concatenate([pos, neg_sampled]))
        X_balanced = X_raw[idx]
        y_balanced = y_raw[idx]
        
        # Format a clean data structure back to disk storage space
        df_balanced = pd.DataFrame(X_balanced, columns=df.columns[1:])
        df_balanced.insert(0, df.columns[0], y_balanced)
        
        df_balanced.to_csv(balanced_csv_path, index=False)
        print(f"   [Data Pipeline] Static balanced dataset safely archived to '{balanced_csv_path}' for future runs.")
        
        return X_balanced, y_balanced

    def preprocess(self, X):
        """Standard preprocessing: PCA reduction to target feature dimension and scaling."""
        pca = PCA(n_components=config.QUBIT_BUDGET, random_state=self.seed)
        X_pca = pca.fit_transform(X)
        scaler = MinMaxScaler(feature_range=(0, np.pi))
        return scaler.fit_transform(X_pca)

def get_all_data(qkernel=None, csv_path=config.CSV_PATH, seed=config.SEED):
    """Convenience helper function to import datasets seamlessly."""
    pipeline = QKEDataPipeline(seed=seed)
    
    # 1. Load Primary Synthetic Data
    X_synth_raw, y_synth = pipeline.generate_synthetic_shells()
    X_synth = pipeline.preprocess(X_synth_raw)
    
    # 2. Load Secondary Local Real Data
    try:
        X_real_raw, y_real = pipeline.load_and_rebalance_real_data(csv_path=csv_path, ratio=config.REAL_DATA_RATIO)
        X_real = pipeline.preprocess(X_real_raw)
    except FileNotFoundError:
        print(f"\n[!] Notice: '{csv_path}' not found in runtime space. Skipping real dataset benchmarks.\n")
        X_real, y_real = None, None
    
    # 3. Load Positive Control Data
    X_qnative, y_qnative = None, None
    if qkernel is not None and X_synth is not None:
        X_qnative, y_qnative = pipeline.generate_quantum_native(X_synth, qkernel)
        
    return (X_synth, y_synth), (X_real, y_real), (X_qnative, y_qnative)


# =====================================================================
# 3. PIPELINE TEST ENGINE & CLASS-WISE VISUALIZATION HUB
# =====================================================================
if __name__ == "__main__":
    class LocalMockKernel:
        def evaluate(self, x_vec, y_vec):
            sq_dists = (
                np.sum(x_vec**2, axis=1, keepdims=True) 
                + np.sum(y_vec**2, axis=1) 
                - 2 * np.dot(x_vec, y_vec.T)
            )
            return np.exp(-0.25 * sq_dists)

    print("Initializing local quantum kernel proxy...")
    mock_kernel = LocalMockKernel()
    
    print("Loading and preprocessing all datasets from the pipeline...")
    (X_synth, y_synth), (X_real, y_real), (X_qnative, y_qnative) = get_all_data(
        qkernel=mock_kernel, 
        csv_path=config.CSV_PATH, 
        seed=config.SEED
    )

    print("\n--- Pipeline Data Diagnostics ---")
    print(f"Primary Synthetic   -> Shape: {X_synth.shape} | Class 0: {np.sum(y_synth==0)}, Class 1: {np.sum(y_synth==1)}")
    if X_qnative is not None:
        print(f"Positive Control    -> Shape: {X_qnative.shape} | Class 0: {np.sum(y_qnative==0)}, Class 1: {np.sum(y_qnative==1)}")
    if X_real is not None:
        print(f"Rebalanced Real CSV -> Shape: {X_real.shape} | Class 0: {np.sum(y_real==0)}, Class 1: {np.sum(y_real==1)}\n")

    # Filter out missing datasets dynamically for rendering safety
    plot_configs = []
    if X_synth is not None:
        plot_configs.append(("Primary Synthetic Data\n(Concentric 8D Shells -> 2D PCA)", X_synth, y_synth))
    if X_qnative is not None:
        plot_configs.append(("Positive Control Data\n(Quantum-Native Encodings)", X_qnative, y_qnative))
    if X_real is not None:
        plot_configs.append(("Rebalanced Real Data\n(Local Fraud CSV -> 2D PCA)", X_real, y_real))

    fig, axes = plt.subplots(1, len(plot_configs), figsize=(6 * len(plot_configs), 5.5))
    if len(plot_configs) == 1:
        axes = [axes]
    
    for idx, (title, X_data, y_data) in enumerate(plot_configs):
        X_plot = PCA(n_components=2, random_state=config.SEED).fit_transform(X_data)
        
        c0 = X_plot[y_data == 0]
        c1 = X_plot[y_data == 1]
        
        axes[idx].scatter(c0[:, 0], c0[:, 1], color='#1f77b4', label='Class 0 (Negative)', alpha=0.6, edgecolors='k', s=40)
        axes[idx].scatter(c1[:, 0], c1[:, 1], color='#ff7f0e', label='Class 1 (Positive)', alpha=0.8, edgecolors='k', s=40)
        
        axes[idx].set_title(title, fontsize=12, fontweight='bold', pad=10)
        axes[idx].set_xlabel("PCA Projection Axis 1", fontsize=10)
        axes[idx].set_ylabel("PCA Projection Axis 2", fontsize=10)
        axes[idx].grid(True, linestyle='--', alpha=0.4)
        axes[idx].legend(loc='upper right', frameon=True)
        
    plt.suptitle("Quantum-Enhanced Kernel Evaluation Data Profiling Hub", fontsize=14, fontweight='bold', y=0.98)
    plt.tight_layout()
    plt.show()